services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mp-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=TuPasswordFuerte123
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: mp-backend
    container_name: mp-backend
    environment:
      - PORT=3001
      - DB_HOST=sqlserver
      - DB_PORT=1433
      - DB_USER=sa
      - DB_PASSWORD=TuPasswordFuerte123
      - DB_NAME=DICRI_EVIDENCIAS
      - JWT_SECRET=MiSecretoSuperSeguro123
    depends_on:
      - sqlserver
    ports:
      - "3001:3001"
    restart: unless-stopped

volumes:
  sql_data:
